version: "3.9"

volumes:
  wordpress_data:
      name: wordpress_data
      driver: local
      driver_opts:
          device: ${HOME}/data/wordpress
          o: bind
          type: none
  mariadb_data:
      name: mariadb_data
      driver: local
      driver_opts:
          device: ${HOME}/data/mariadb
          o: bind
          type: none

networks:
  inception:
    driver: bridge

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
     - "443:443"
    volumes:
     - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000"
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "21:21"
      - "21100-21110"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    build: ./requierements/bonus/adminer/.
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception
    restart: always
    